### ISSUE TITLE
Add settings link in plugin overview area

### ISSUE THREAD

**Issue by mariobehling** [fossasia/wp-tweets-widget#12]
There is a "connect to twitter" link, but the standard of most other plugins is to show a settings button. Please follow this and add a "settings" button linking to the settings/connect to twitter area.

![screenshot from 2016-08-27 15 46 47](https://cloud.githubusercontent.com/assets/1583873/18027804/bbb45d98-6c6d-11e6-9698-3e5ce4d541b6.png)

**Comment by sopu** [comment]
Currently it looks like this.
![selection_021](https://cloud.githubusercontent.com/assets/6399612/18050179/a2f8ee60-6e0a-11e6-9c56-2b7af675e249.png)

**Comment by sopu** [comment]
Currently it looks like this.
![selection_021](https://cloud.githubusercontent.com/assets/6399612/18050179/a2f8ee60-6e0a-11e6-9c56-2b7af675e249.png)
@mariobehling

**Comment by sopu** [comment]
Closing!

**Comment by mariobehling** [comment]
@sopu Please compare to other plugins: "Settings" should be next to "deactivate | edit"

**Comment by sopu** [comment]
Fixed! 
![selection_027](https://cloud.githubusercontent.com/assets/6399612/18053127/9ee69866-6e1b-11e6-97c3-415a54841131.png)
@mariobehling

**Comment by sopu** [comment]
Closing!!
